### PR TITLE
Totaly changed this folder

### PR DESCRIPTION
**Pull request by Cing2**
Hi Lupus,
I have done a lot to you design doc folder and you probably won't recognize. I left as much of you notes in my file's but I sorted them in my different folders and file's. 

You will be probably want to take a look in the files and change something's or add it isn't totally finished yet but most of the things are in there. 

But I hope this will help the project.

### CODE REVIEW

**Comment by Lupus590** [comment]
Please read those note commits

**Comment by Cing2** [comment]
By interface I only mean the thing the user will see (AKA just the screens) 
The rest will be done by the server part

**Comment by Cing2** [comment]
The first note is also good if you asked that.

**Comment by Lupus590** [comment]
@Cing2 Could you work on organising links.md please?

**Comment by Cing2** [comment]
I Will look in to that

**Pull request merged**
